Exploring PyTorch Functions

Getting to know about few PyTorch Tensor Functions 

An short introduction about PyTorch and about the chosen functions. 

- torch.transpose
- torch.cartesian_product
- torch.reshape
- torch.histc
- torch.trace

In [2]:
# Import torch and other required modules
import torch

 Function 1 - torch.transpose 
 
 This functions returns the transposed version of the tensor. 

In [8]:
# Example 1 - Initializing a random tensor using randn()
x = torch.randn(3,2)
x
torch.transpose(x,0,1)

tensor([[-0.7591, -1.4804, -1.8934],
        [ 0.7398, -0.2305,  1.1969]])

first we have a matrix of 3 rows and 2 columns and after we use the transpose functions, it just transposes to 2 rows and 3 columns.

In [9]:
# Example 2 
y = torch.rand(4,5)
y
torch.transpose(y,1,1)

tensor([[0.7116, 0.4837, 0.5610, 0.8980, 0.4105],
        [0.5422, 0.6253, 0.3854, 0.3304, 0.3193],
        [0.1751, 0.4487, 0.0626, 0.0229, 0.5867],
        [0.5795, 0.2378, 0.8937, 0.9924, 0.9855]])

Explanation about example

In [10]:
# Example 3 - breaking (to illustrate when it breaks)
z= torch.randn(3,2)
z
torch.transpose(z,0)

TypeError: transpose() received an invalid combination of arguments - got (Tensor, int), but expected one of:
 * (Tensor input, name dim0, name dim1)
 * (Tensor input, int dim0, int dim1)


to transpose a given matrix , we need to give a proper dimensions, here I didn't give the dimensions of the matrix z.

So, to properly transpose a matrix using torch.transpose(), the arguments which is the matrix to be transposed and its dimensions should be given properly.

<b>Function 2- torch.cartesian_prod()</b>


It is the product of two tensors. The result will be a tensor where all the ordered pairs of both input tensors are present. The input tensors can be a sequence of lists. 

In [14]:
# Example 1 
x = [1,2,3]
y = [4,5,6]
tensor_x = torch.tensor(x)
tensor_y = torch.tensor(y)
torch.cartesian_prod(tensor_x,tensor_y)

tensor([[1, 4],
        [1, 5],
        [1, 6],
        [2, 4],
        [2, 5],
        [2, 6],
        [3, 4],
        [3, 5],
        [3, 6]])

The result tensor is a product of x and y where all the elements of x are paired with all the elements of y. 

In [16]:
# Example 2 - 
a = [8,9]
b = [6,7]
tnsr_a = torch.tensor(a)
tnsr_b = torch.tensor(b)
c = torch.cartesian_prod(tnsr_a,tnsr_b)
c

tensor([[8, 6],
        [8, 7],
        [9, 6],
        [9, 7]])

The tensor c is the paired tensor of a and b. verifying all the elements of a and b are present in c. 

In [21]:
# Example 3 - breaking (to illustrate when it breaks)
a = [1,2,3]
b = [1,2.3,3]
tensor_a = torch.tensor(a)
tensor_b = torch.tensor(b)
c = torch.cartesian_prod(tensor_a,tensor_b)
c

RuntimeError: meshgrid expects all tensors to have the same dtype

The input tensor should always have the same data type. 

The above example throws an error since the data type of the second list is not integer.

Function 3 - torch.reshape()

This function reshapes your tensor into another shape ,and returns with the same data and number of elements.




In [3]:
# Example 1 - 
a = torch.arange(4.)
torch.reshape(a, (2, 2))

tensor([[0., 1.],
        [2., 3.]])

In this example, we reshape our tensor a which has 4 elements into a (2,2) matrix.

In [13]:
# Example 2 - working
x = torch.randn((1,14))
print(x)
torch.reshape(x,(7,2))

tensor([[ 0.4908,  1.5436, -1.7414, -0.0169,  0.6341, -0.2447,  1.2378,  0.5317,
         -0.6539, -0.3933, -0.1732,  0.6391, -0.1920,  0.1571]])


tensor([[ 0.4908,  1.5436],
        [-1.7414, -0.0169],
        [ 0.6341, -0.2447],
        [ 1.2378,  0.5317],
        [-0.6539, -0.3933],
        [-0.1732,  0.6391],
        [-0.1920,  0.1571]])

In this example, we reshape our tensor x which has 14 elements into a (7,2) matrix.

In [14]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.randn((1,11))
print(x)
torch.reshape(x,(3,4))

tensor([[-0.8382,  0.4820,  0.1376, -0.5426,  0.9313,  0.6928, -1.3618, -0.3195,
         -0.4483,  0.7505,  0.1872]])


RuntimeError: shape '[3, 4]' is invalid for input of size 11

in the above example, my input random numbers is 11 elements and the reshaping arguments is bigger than that which is why we get an error

While reshaping a matrix, we have to make sure the size of the input matrix and the shape of the resulting matrix should be the same.

Funtion 4- torch.histc()

Computes the historgram of a tensor

In [25]:
# Example 1 - working
tensor_a = torch.tensor([1.,2,1])
torch.histc(tensor_a, bins=4, min=0, max=3)

tensor([0., 2., 1., 0.])

The input tensor is being shown as a histogram of a tensor with 4 bars with the minimum as zero and the max range.

In [27]:
# Example 2 - working
#tensor_x = torch.tensor([1,2,3])
torch.histc(torch.tensor([1,2.,3]), bins= 4, min=0, max=3)

tensor([0., 1., 1., 1.])

The input tensor is being shown as a histogram of a tensor with 4 bars with the minimum as zero and the max range.

In [29]:
# Example 3 - breaking (to illustrate when it breaks)
torch.histc(torch.tensor([1,2.,3]), bins= 4, min=4, max=3)

RuntimeError: max must be larger than min

The argument min should be the lower end of the range. 

Always make sure the histogram arguments should be the min and the maximum. 

Function 5 - torch.trace

Returns the sum of the elements of the diagonal of the input 2-D matrix.

In [38]:
# Example 1 - working

x = torch.arange(1., 10.).view(3, 3)
print(x)
torch.trace(x)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


tensor(15.)

the input tensor is from elements 1 through 10. and the resulting value is the sum of the diagonal elements. 

In [39]:
# Example 2- breaking (to illustrate when it breaks)
x = torch.arange(1., 10.).view(3, 5)
print(x)
torch.trace(x)

RuntimeError: shape '[3, 5]' is invalid for input of size 9

the input tensor elements are 10 and the display matrix is more than the dimensions, so, its throwing an error

So, be careful with the dimensions of the input tensor matrix. 

Conclusion

In this notebook, we discussed few tensor functions that are in PyTorch. To learn more, you can visit
https://pytorch.org/docs/master/torch.html

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* ...